apiVersion: envoy.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: policy
spec:
  evaluation:
    mode: Envoy
  validations:
  - expression:
      # envoy.Allowed().Response()
      envoy.Denied(403).Response()